synclias/blueprints/sites/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField
from wtforms.validators import DataRequired


class AddSiteForm(FlaskForm):
    url = StringField('URL', validators=[DataRequired()])
    submit = SubmitField('AddSite')

synclias/blueprints/sites/views.py
from flask import Blueprint
from flask import request
from flask import url_for, jsonify, redirect, abort, flash, render_template

from tldextract import tldextract
from flask_login import login_required
from .forms import AddSiteForm
from synclias.models import Site

from synclias import db
from sqlalchemy import select
from flask import current_app

sites = Blueprint("sites", __name__, template_folder="templates")

@sites.route("/", methods=["GET","POST"])
@login_required
def site():
    if request.method == "GET":
        add_site_form = AddSiteForm()
        
        ## Pagination work - calculate entries on this page, next/prev pages. "1" = Page 1 of results, overriden if parameter "page" passed
        page = request.args.get('page', 1, type=int)
        sites = Site.query.order_by('url_group').paginate(page=page,per_page=10)
        
        next_url = url_for('sites.site', page=sites.next_num) \
        if sites.has_next else None
        prev_url = url_for('sites.site', page=sites.prev_num) \
        if sites.has_prev else None

        return render_template("/site.html", sites=sites, add_site_form=add_site_form, next_url=next_url, prev_url=prev_url)

    else:
        ### Sanitise input
        # No form
        if not request.form:
            abort(400)
        
        # Remove whitespace, common in copy/pasted urls
        url = request.form.get('url')
        if url is None:
            abort(400)

        url = url.strip()

        ## No wildcards check
        if '*' in url:
            flash(f"Wildcards aren't possible - rejecting {url}")
            return redirect(url_for("sites.site"))
        
        ## Checkit loos like a hostname and get it's domain
        tld = tldextract.extract(request.form.get('url')) # type: ignore
        if not tld.fqdn:
            flash(f"Site supplied {url} not understood, rejecting",'info')
            return redirect(url_for("sites.site"))           
        
        already_present = db.session.scalars(select(Site).where(Site.url == tld.fqdn)).all()
        if already_present:
            flash(f"Site: {tld.fqdn} already present",'info')
            return redirect(url_for("sites.site"))

        ## Build and save new site.
        site = Site(
            url=tld.fqdn, # type: ignore
            url_group=tld.top_domain_under_public_suffix # type: ignore
        )
        db.session.add(site)
        db.session.commit()
        return redirect(url_for("sites.site"))


@sites.route('/delete_bulk/', methods=["POST"])
@login_required
def delete_bulk():

    for key in request.form.keys():
        if key.startswith('select'):
            to_delete = key.split('-')[1]
            current_app.logger.info(f"{to_delete}")
            site = db.session.get(Site,to_delete)
            if site is not None:
                site_url = site.url
                db.session.delete(site)
                db.session.commit()
                flash(f"Deleted: {site_url}")
            else:
                ## Genuinely amazed if you get here, but never say never.
                flash(f"Error finding site {to_delete}")
    return redirect(url_for("sites.site"))

@sites.route('/delete/<int:id>', methods=["POST"])
@login_required
def delete(id):
    site = db.get_or_404(Site, id)
    db.session.delete(site)
    db.session.commit()
    return redirect(url_for("sites.site"))

@sites.route("/<string:option>/<int:id>/<int:new_state>", methods=['PUT'])
@login_required
def update_site_option(option,id,new_state):
    target = Site.query.get_or_404(id)

    ## Check it's valid, but not in columns we don't update
    if option in target.to_json().keys() and option not in ['id','url','url_group']:

        current_app.logger.debug(f"Toggle site {id} option {option} to {new_state}")
        
        ## Sanity checked enough, trust what we've got
        setattr(target,option,new_state)

        db.session.commit()
        return jsonify({ 'site' : id, 'option': option, 'setting': new_state},200)
    else:
        abort(400)


@sites.route("/create/bulk/", methods=["POST"])
@login_required
def create_bulk_site():

    ## data format received - [('site1', 'www.foo.com'), ('site2', 'www.bar.com')....]
    for row in request.form.items():

        to_add = row[1]

        if '*' in to_add:
            flash(f"Wildcards aren't possible - rejecting {to_add} (I'm not sure how you got that in there!)",'info')
            continue
        
        current_app.logger.debug(f"Got site: {to_add}, looking in DB")
        in_db = db.session.query(Site).filter_by(url = to_add).first()
        if not in_db:
            current_app.logger.debug(f"Not found, adding")
            tld = tldextract.extract(to_add)
            site = Site(
                url = to_add, # type: ignore
                url_group=tld.top_domain_under_public_suffix, # type: ignore
            )
            db.session.add(site)
            db.session.commit()
        else:
            flash(f"Site: {to_add} already present",'info')
            current_app.logger.debug(f"Already in database, skipping {to_add}")

    return redirect(url_for("sites.site"))

synclias/blueprints/sites/templates/site.html
{% extends "base.html" %}

{% block title %}Synclias{% endblock %}

{% block page_content %}

    <!-- Modal for Adding Site-->
    <div class="modal fade" id="add-site-modal" tabindex="-1" aria-labelledby="add-site-modal-label" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="add-site-modal-label">Add Routed Site</h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <form action="{{url_for('sites.site')}}" method="post">
            {{ add_site_form.hidden_tag() }}
            <div class="modal-body">
              <div class="form-group row">
                {{ add_site_form.url.label }}
                <!-- <label for="url" class="col-xs-2 control-label">URL</label> -->
                <div class="col-xs-10">
                    {{ add_site_form.url(size=32,class="form-control") }}
                  
                    {% for error in add_site_form.url.errors %}
                    <span style="color: red;">[{{ error }}]</span>
                    {% endfor %}

              <!-- <input type="text" id="url" class="form-control" name="url" placeholder="www.site.com" /> -->
                </div>
              </div>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
              <button type="submit" class="btn btn-success">Add</button>
            </div>
          </form>
        </div>
      </div>
    </div>
    <!-- Modal End: Add Site-->

      </br>
      <h1>VPN Routed Sites</h1>

      <p>Note: Only complete URLs will work (no wildcards!)</p>

      <div class="row">
        <div class="col-md-2">
          <button type="button" class="btn btn-success" data-bs-toggle="modal" data-bs-target="#add-site-modal">
            Add Site
          </button>
        </div>
        <div class="col-md-3">
          <button type="submit" form="form-select-sites" class="btn btn-danger">Delete Selected</button>
        </div>
        
        <div class="col-md-4">
        </div>
      </div>
    </br>

      


      <div class="row">
        <div class="col-md-8">
          <form id="form-select-sites" action="{{url_for('sites.delete_bulk')}}" method="post">
            <table class="table table-striped" border="1">
              <thead>
                <tr>
                  <th>
                    <div class="form-check">
                      <input class="form-check-input" type="checkbox" value="" onclick=toggle_selection(this.id,this.checked) name="check-all" id="check-all">
                        <label class="form-check-label" for="flexCheckDefault"></label>
                    </div>
                  </th>
                  <th>Site</th>
                  <th>Site Group</th>
                  <th>Scan on Sync?</th>
                  <th>Override Safety Keywords?</th>
                  <th>Also use Historical DNS?</th>
                  <!-- <th colspan="2">Action</th> -->
                </tr>
              </thead>
              <tbody>
                {% for site in sites %}
                <tr>
                  <!-- <td>{{ site.id }}</td> -->
                  <td>
                    <div class="form-check">
                      <input class="form-check-input" type="checkbox" value="" name="select-{{site.id}}" id="select-{{site.id}}">
                        <label class="form-check-label" for="flexCheckDefault"></label>
                    </div>
                  </td>
                  <td>{{ site.url }}</td>
                  <td>{{ site.url_group }}</td>
                  <td>
                    <div class="form-check form-switch">
                      {% if site.crawl is true %}
                      <input class="form-check-input" type="checkbox" onclick="toggle_property(this.id, this.checked)" name="crawl-{{site.id}}" id="crawl-{{site.id}}" checked="checked">
                      {% else %}
                      <input class="form-check-input" type="checkbox" onclick="toggle_property(this.id, this.checked)" name="crawl-{{site.id}}" id="crawl-{{site.id}}" >
                      {% endif %}
                    </div>
                  </td>
                  <td>
                    <div class="form-check form-switch">
                      {% if site.override_safety is true %}
                      <input class="form-check-input" type="checkbox" onclick="toggle_property(this.id, this.checked)" name="override_safety-{{ site.id}}" id="override_safety-{{ site.id}}" checked="checked">
                      {% else %}
                      <input class="form-check-input" type="checkbox" onclick="toggle_property(this.id, this.checked)" name="override_safety-{{ site.id}}" id="override_safety-{{ site.id}}" >
                      {% endif %}
                    </div>
                  </td>
                  <td>
                    <div class="form-check form-switch">
                      {% if site.use_dns_history is true %}
                      <input class="form-check-input" type="checkbox" onclick="toggle_property(this.id, this.checked)" name="use_dns_history-{{ site.id}}" id="use_dns_history-{{ site.id}}" checked="checked">
                      {% else %}
                      <input class="form-check-input" type="checkbox" onclick="toggle_property(this.id, this.checked)" name="use_dns_history-{{ site.id}}" id="use_dns_history-{{ site.id}}" >
                      {% endif %}
                    </div>
                  </td>
                  <!-- <td><button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#delete-site-modal_{{ site.id}}">Delete</button></td> -->
              
                  <!-- Modal for deleting a site -->
                  <div class="modal fade" id="delete-site-modal_{{ site.id}}" tabindex="-1" aria-labelledby="delete-site-modal-label" aria-hidden="true">
                    <div class="modal-dialog">
                      <div class="modal-content">
                        <div class="modal-header">
                          <h5 class="modal-title" id="delete-site-modal-label">Delete Site</h5>
                          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                        </div>
                        <form action="{{url_for('sites.delete', id=site.id)}}" method="post" name="delete-site-modal-form" id="delete-site-modal-form">
                          <div class="modal-body">
                            <div class="form-group row">
                              <label class="col-sm-12 col-form-label">Do you want to delete the site <spa style='font-weight:bold;color:red'>{{site.url}}</span>?</label>
                            </div>
                          </div>
                          <div class="modal-footer">
                            <button type="button" class="btn btn-default" data-bs-dismiss="modal">Close</button>
                            <button type="submit" form="delete-site-modal-form" class="btn btn-danger">Delete</button>
                          </div>
                        </form>
                      </div>
                    </div>
                  </div>
                      <!-- End Modal-->
                </tr>
                {% endfor %}
              </tbody>
            </table>
          </form>
        </div>
      </div>
      <div class="col-md-8">
          <nav aria-label="..."> 
        <ul class="pagination justify-content-end">
          <li class="page-item  {{'disabled' if not prev_url}}">
            <a class="page-link" href="{{ prev_url }}">Prev</a>
          </li>

          {% for page_no in range(sites.pages) %}
            <!-- {{ sites.page }} -->
            {% if loop.index == sites.page %}
              <li class="page-item active"> <span class="page-link"> {{ loop.index }} </span> </li>
              <!-- {{ loop.index }} -->
            {% else %}
              <li class="page-item" ><a class="page-link" href="{{ url_for('sites.site', page= loop.index) }}">{{ loop.index }}</a></li>
            {% endif%}
          {% endfor %}
          <li class="page-item  {{'disabled' if not next_url}}">
            <a class="page-link" href="{{ next_url }}">Next</a>
          </li>
        </ul>
      </nav>
        </div>




{% endblock %}

{% block scripts %}

    {{ super() }}

    <script>

      // checkbox for "select all"
      function toggle_selection(id,checked){
        $("[name^='select-']").each(function(){
          this.checked = checked
        })
      }

      // Ajax PUT for any of the toggle switches to modify settings in db
      function toggle_property(id,state){
        const splitArray = id.split("-");
        // I know I'm converting True to 0/1, and it's a newbie error
        state === true ? state_int = 1 : state_int = 0

        url = "/site/" + splitArray[0] + "/" + splitArray[1] + "/" + state_int;
        $.ajax({
          type: 'PUT',
          url: url, 
        });
      }
     
    </script>

{% endblock %}