synclias/blueprints/asndb/views.py
from flask import Blueprint
from flask import request
from flask import url_for, jsonify, abort, redirect, flash, render_template
from flask_login import login_required

import tldextract

from .forms import AddASNForm, LookupASNForm

from flask import current_app
from synclias import db

from synclias.models import ASN

asndb = Blueprint("asns", __name__, template_folder="templates")

## Main ASN page
# GET - list ASNs/Lookup form
# POST - if we've got a valid form, load the page (will keep the data) and "start lookup" (Triggers modal open and lookup task)
#      - if no valid form (somehow) - present the page an error and let user figure it out
@asndb.route("/", methods=('GET','POST'))
@login_required
def page():

    add_asn_form = AddASNForm()
    lookup_asn_form = LookupASNForm()
    asns = db.session.query(ASN).all()
    
    if request.method == "GET":
        return render_template("/asn.html", asns=asns, add_asn_form=add_asn_form, lookup_asn_form=lookup_asn_form)
    
    ## Lookup
    ## Add ASN posts to another core, so this MUST be an ASN lookup, handle as such
    if lookup_asn_form.validate_on_submit():
        return render_template("/asn.html", asns=asns, add_asn_form=add_asn_form, lookup_asn_form=lookup_asn_form, start_lookup=True)  
    else:
        ## Just in case
        current_app.logger.info("Post, no lookup data data")
        return render_template("/asn.html", asns=asns, add_asn_form=add_asn_form, lookup_asn_form=lookup_asn_form)

## Create ASN route
@asndb.route("/create", methods=["POST"])
@login_required
def create():
    if not request.form:
        current_app.logger.debug("Rejecting for lack for form")
        abort(400)
    current_app.logger.debug(request.form)
    if (request.form.get('comment')).startswith('ERROR-'): # type: ignore
        temp_comment = "Unknown"
    else:
        temp_comment = request.form.get('comment')
    asn = ASN(
        asn=request.form.get('asn'), # type: ignore
        comment = temp_comment, # type: ignore
    )
    db.session.add(asn)
    db.session.commit()
    return redirect(url_for("asns.page"))

## Get ASN DB Stats (file info)
# Used by Home/Status page, and called by the downloader status check to see if files are actually growing
@asndb.route("/stats", methods=["GET"])
@login_required
def get_asndb_stats():
    from synclias.blueprints.asndb.tasks import get_asn_file_info
    response = get_asn_file_info()
    return jsonify(response)

## Lookup ASN info posted from main page form
## Takes a string, extracts tld from it, uses that to lookup asn/bgp and returns
## TODO - Better naming - "find" vs "get site" function naming is ambiguous
@asndb.route("/find/", methods=['POST'])
@login_required
def find_site_asn_bgp():
    
    url = request.get_json()
    url_site = url['site']

    ## Get the tld from whatever was supplied
    tld = (tldextract.extract(url_site)).top_domain_under_registry_suffix # type: ignore
    current_app.logger.debug(f"Looking up {tld}")
    
    ## Lookup 
    if not tld is None:
        from synclias.blueprints.asndb.tasks import get_site_asn_bgp
        response = get_site_asn_bgp(tld)
    else:
        response = {
            'found' : False,
            'asn' : "Error",
            'asn_name' : "Couldn't find domain in supplied text",
            'bgp' : "Error",
            'subnet_count' : "Error",
            'asn_ip_count' : "Error",
        }

    return jsonify(response)

## Delete - can't directly use DELETE without ajax, browsers don't make them - so it's a POST for now
## Called by Delete button on ASN Page
@asndb.route('/delete/<int:id>', methods=["POST"])
@login_required
def delete(id):
    asn = db.get_or_404(ASN, id)
    db.session.delete(asn)
    db.session.commit()
    flash(f"Deleted ASN: {asn.asn}","info")
    return redirect(url_for("asns.page"))

## ASN DB Download task monitoring
@asndb.route('/download_asndb/status/<task_id>', methods=['GET'])
@login_required
def download_asndb_status(task_id):
    ## This really sucks, we have to launch external 3 external scripts to get/convert the files, those scripts are better than I could ever hope to write though
    ## BUT the download servers can be a little "iffy" there's a real chance it stalls out, so let's monitor what we can

    ## For reference, the three files we'll get/create:
    #ASNDB_TEMP_RIB_FILE = 'latest.rib' -- Downloads first, if this is going to timeout, it'll be here, average download time, 5-10 mins, size: ~80MB
    #ASNDB_FILE = 'asndb' -- Created locally by converting the TEMP_RIB_FILE      
    #ASNDB_NAMES_FILE = 'asn_names' -- Created from downloads from multiple sites (HTTP) and collating
    from synclias.blueprints.asndb.tasks import get_asn_file_info
    from synclias.blueprints.asndb.tasks import download_asn_db_and_names
    task = download_asn_db_and_names.AsyncResult(task_id)
    if task.state == 'PENDING':
    # job did not start yet
        response = {
            'state': task.state,
            'current_step' : "Pending...",
            'message' : 'Awaiting scheduling...',
            'status': task.info.get('status'),
        }
    elif task.state != 'FAILURE':
    ## Task is currently running, let's get some stats at least
 
        ## Work out what we can get info on
        if task.info.get('current_step') == '1/3 - DB Download':
            stats = get_asn_file_info()
            messagetext = f"Currently downloading, have {stats['ASNDB_TEMP_RIB_FILE']['size_mb']} MB, last updated {stats['ASNDB_TEMP_RIB_FILE']['modified']} expected file size ~60-80MB"
            current_app.logger.debug(f"Stats: {stats}")
            current_app.logger.debug(messagetext)
            response = {
                'state': task.state,
                'current_step' : '1/3 - DB Download',
                'message' : messagetext,
                'status': task.info.get('status'),
            }

        elif task.info.get('current_step') == '2/3 - Converting':
            ## No point in getting file info, this just needs to run, it'll finish
            response = {
                'state': task.state,
                'current_step' : '2/3 - Converting',
                'message' : f"Converting downloaded file, this can take up to 5 minutes",
                'status': task.info.get('status'),
            }

        elif task.info.get('current_step') == '3/3 - Names Download':
            ## No point in getting file info, nothing to monitor as it's all in memory until the final write out to disk
            response = {
                'state': task.state,
                'current_step' : '3/3 - Names Download',
                'message' : f"Grabbing ASN names file, this can take up to 5 minutes",
                'status': task.info.get('status'),
            }

        elif task.info.get('current_step') == 'Completed!':
            ## No point in getting file info, nothing to monitor as it's all in memory until the final write out to disk
            response = {
                'state': task.state,
                'current_step' : 'Completed!',
                'message' : f"Completed!",
                'status': task.info.get('status'),
            }

        if 'result' in task.info:
            response = {
                'state': task.state,
                'current_step' : 'Completed!',
                'message' : f"Completed!",
                'status': task.info.get('status'),
            }
            response['result'] = task.info['result']
    else:
        # Task status is FAILED
        response = {
            'state': task.state,
            'current_step' : 'N/A',
            'message' : str(task.info),  # this is the exception raised
            'status': task.info.get('status'),
        }

    ### This set of tests is broken, but in a working way.....
    if task.state == 'SUCCESS':
        current_app.logger.debug(f"Complete!")

        response = {
            'state': task.state,
            'current_step' : 'Completed!',
            'message' : f"Completed!",
            'status': task.info.get('status'),
        }

    return jsonify(response)

## Trigger downloading of the ASN Database
## This can take a while, so background it
## Return task id after creation, ajax on page will use task status above to monitor
@asndb.route("/download_asndb", methods=["POST"])
@login_required
def download_asndb():
    from synclias.blueprints.asndb.tasks import download_asn_db_and_names
    task = download_asn_db_and_names.delay()
    return jsonify({}), 202, {'Location': url_for('asns.download_asndb_status', task_id=task.id)}

synclias/blueprints/asndb/templates/asn.html
{% extends "base.html" %}

{% block title %}Synclias{% endblock %}

{% block page_content %}
<br>
<div class="container-fluid">
	<div class="row">
		<div class="col-md-11">
			<h1>
				ASNs
			</h1>
			<p>
        ASNs are groups of networks that are managed by a single company<br>
        WARNING: Adding huge ASNs (Like Amazon or Google) really isn't recommended, it's more likely to break more things
			</p>
			<h3>
				ASN Lookup
			</h3>
		</div>
		<div class="col-md-1">
		</div>
	</div>
	<div class="row">
		<div class="col-md-8">
      <form action="{{url_for('asns.page')}}" method="post">
        <table class="table" border="1">
          <tr> {{ lookup_asn_form.hidden_tag() }}
            <td>{{ lookup_asn_form.target.label }}</td>
            <td>
              {{ lookup_asn_form.target(size=32,class="form-control") }}  
              {% for error in lookup_asn_form.target.errors %}
              <span style="color: red;">[{{ error }}]</span>
              {% endfor %}
            </td>
          <!-- <td><input type="text" id="asn-lookup" class="form-control" name="asn-lookup" placeholder="ns1.site.lan" /></td> -->
          <td>
            <!-- <button submit data-bs-toggle="modal" data-bs-target="#lookup-asn-modal" id="lookup-button" onclick="disable_add_button()" class="btn btn-success">Lookup</button></td> -->
            <button submit id="lookup-button" class="btn btn-success">Lookup</button></td>
          </tr>
        </table>
      </form>
		</div>
		<div class="col-md-3">
		</div>
		<div class="col-md-1">
		</div>
	</div>
  <div class="row">
    <div class="col-md-12">
		 <table class="table" border="1">
            <tr>Legal Note: The ASN DB Data is provided by RouteViews<br> </tr>
            <tr>This data is licensed by the Creative Commons v4 with Attribution license </tr>
            <tr>visible at <a href="https://creativecommons.org/licenses/by/4.0/.">Creative Commons Org</a><br></tr>
            <tr><a href="https://www.routeviews.org">RouteViews Project Website</a></tr>
      </table>
    </div>
  </div>

  <div class="row">
		<div class="col-md-7">
      <br>
      <h3>VPN Routed ASNs</h3>
    </div>
  </div>

  <div class="row">
    <div class="col-md-12">
      <button type="button" class="btn btn-success" data-bs-toggle="modal" data-bs-target="#add-asn-modal">
        Add ASN
      </button>
    </div>
  </div>

  <br>
  <div class="row">
		<div class="col-md-8">
          <table class="table" border="1">
        <thead>
          <tr>
            <th>ASN</th>
            <th>Comment</th>
            <th colspan="2">Action</th>
          </tr>
        </thead>
        <tbody>
          {% for asn in asns %}
          <tr>
            <!-- <td>{{ asn.id }}</td> -->
            <td>{{ asn.asn }}</td>
             <td>{{ asn.comment }}</td>
            <td><button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#delete-asn-modal_{{ asn.id}}">Delete</button></td>
        
            <!-- Modal for deleting a asn -->
            <div class="modal fade" id="delete-asn-modal_{{ asn.id}}" tabindex="-1" aria-labelledby="delete-asn-modal-label" aria-hidden="true">
              <div class="modal-dialog">
                <div class="modal-content">
                  <div class="modal-header">
                    <h5 class="modal-title" id="delete-asn-modal-label">Delete ASN</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                  </div>
                  <form action="{{url_for('asns.delete', id=asn.id)}}" method="post">
                    <div class="modal-body">
                      <div class="form-group row">
                        <label class="col-sm-12 col-form-label">Do you want to delete the asn <spa style='font-weight:bold;color:red'>{{asn.asn}}</span>?</label>
                      </div>
                      </div>
                    <div class="modal-footer">
                      <button type="button" class="btn btn-default" data-bs-dismiss="modal">Close</button>
                      <button type="submit" class="btn btn-danger">Delete</button>
                    </div>
                  </form>
                </div>
              </div>
            </div>
            <!-- End Modal-->
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
    <div class="col-md-3">
    </div>
		<div class="col-md-1">
    </div>
  </div>
</div>

 <!-- Modal for Adding Single ASN-->
  <div class="modal fade" id="add-asn-modal" tabindex="-1" aria-labelledby="add-asn-modal-label" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="add-asn-modal-label">Add ASN</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <form action="{{url_for('asns.create')}}" method="post">
          {{ add_asn_form.hidden_tag() }}
          <div class="modal-body">
            <div class="form-group row">
              <table>
                <tr>
                  {{ add_asn_form.asn.label }}
                  {{ add_asn_form.asn(size=32,class="form-control") }}  
                  {% for error in add_asn_form.asn.errors %}
                  <span style="color: red;">[{{ error }}]</span>
                  {% endfor %}
                </tr>
                <tr>
                  {{ add_asn_form.comment.label }}
                  {{ add_asn_form.comment(size=32,class="form-control") }}
                  {% for error in add_asn_form.comment.errors %}
                  <span style="color: red;">[{{ error }}]</span>
                  {% endfor %}
                </tr>
              </table>
            </div>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
            <button type="submit" class="btn btn-success">Add</button>
          </div>
        </form>
      </div>
    </div>
  </div>
  <!-- Modal End: Add ASN-->

  <!-- Modal for looking up a website's ASN -->
  <div class="modal fade" id="lookup-asn-modal" tabindex="-1" data-bs-backdrop="static" data-bs-keyboard="false" aria-labelledby="lookup-asn-modal-label" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <div class="container">  
            <div class="row">
              <div class="col-auto me-auto">
                <h5 class="modal-title" id="lookup-url-modal-label">Lookup ASNs</h5>
              </div>
              <div class="col-auto">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal" id="dismiss-button">Cancel</button>
                <button type="submit" form="submit-asn" id="add-asn-modal-button" class="btn btn-success" >Add ASN</button>
              </div>
            </div>
          </div>
        </div>
        <div class="modal-body">
          <div><p></p></div>
          <!-- Placeholder to be replaced with status/results form -->
          <div id="asn-results"></div>
        </div>
        <div class="modal-footer">
        </div>
      </div>
    </div>
  </div>
  <!-- End Modal-->



{% endblock %}


{% block scripts %}
    {{ super() }}

    {% if start_lookup %}
      <script>
        console.log("Got here by post and start_lookup")
        $(document).ready(function(){
          disable_add_button()
          $("#lookup-asn-modal").modal('show');
          trigger_lookup()
        });
      </script>
    {% endif %}

    <script>
      function clear_data(){
        $('#asn-results').replaceWith('<div id="asn-results"></div');
        $('#add-asn-modal-button').prop('disabled', true);
      }

      function trigger_lookup() {
            
        div = $('<div class="spinner-border text-primary" role="status"> <span class="visually-hidden">Loading...</span></div>');
        $('#asn-results').append(div);

        var site_url = document.getElementById("target").value;
        var lookup_url = '/asn/find/';
        var data =  JSON.stringify({ "site": site_url });
        console.log("Sending " + data)
        
        fetch('/asn/find/', {
          method: 'POST',
          headers: {
              'Accept': 'application/json',
              'Content-Type': 'application/json'
          },
          body: data
        })
        .then((response) => {

          if (response.ok) {
            return response.json();
          }
          return Promise.reject(response); 
        })

        .then(response => {

          asn_results_start = '<div id="asn-results">';

          if (data['scan_rcode'] >= 400) {
            warning = '<div class="bg-danger text-white">WARNING: ASN DB Missing, please download it and try again</br></div>';
          } else {
            warning = '';
          }
          table_start = '<form id="submit-asn" action="{{url_for("asns.create")}}" method="post"><table class="table" border="1">';

          // Yes, all this is truly horrible, I should be passing the labels and looping
          
          table_rows = '';
          table_rows = table_rows + '<input type="hidden" id="asn" name="asn" value="' + response['asn'] + '">';
          table_rows = table_rows + '<input type="hidden" id="comment" name="comment" value="' + response['asn_name'] + '">';
          table_rows = table_rows + '<tr>';
          table_rows = table_rows + '  <td> ASN </td>';
          table_rows = table_rows + '  <td><label for="' + response['asn'] + '">' + response['asn'] + '</label></td>';
          table_rows = table_rows + '</tr><tr>';
          table_rows = table_rows + '  <td> ASN Name </td>';
          table_rows = table_rows + '  <td>' + response['asn_name'] + '</td>';
          table_rows = table_rows + '</tr><tr>';
          table_rows = table_rows + '  <td> URL Subnet </td>';
          table_rows = table_rows + '  <td>' + response['bgp'] + '</td>';
          table_rows = table_rows + '</tr><tr>';
          table_rows = table_rows + '  <td> ASN Subnet Count</td>';
          table_rows = table_rows + '  <td>' + response['subnet_count'] + '</td>';
          table_rows = table_rows + '</tr><tr>';
          table_rows = table_rows + '  <td> ASN IP Address Count</td>';
          table_rows = table_rows + '  <td>' + response['asn_ip_count'] + '</td>';
          table_rows = table_rows + '</tr>';

          table_end = '</table></form>';

          asn_results_end = '<div>'

          // Turn the safety on if needed
          if (response['subnet_count'] > 20 || response['asn_ip_count'] > 50000 ){
            warning = '<div class="bg-warning text-black">WARNING: This is a large number of IPs</br>It will probably cause unknown sites to go over the VPN<br></div>';
            warning = warning + '';

            warning = warning + '<div class="bg-danger text-white">I understand, unlock the button';
            warning = warning + '<div class="form-check form-switch">';
            warning = warning + '<input class="form-check-input" type="checkbox" id="safetycatch" name="safetycatch" onclick="safety_catch(this)" value="">';
            warning = warning + '</div></div>';
            
          } else {
            $('#add-asn-modal-button').prop('disabled', false);
          }

          // $('#add-asn-modal-button\=').prop('disabled', false);
          modal_contents = asn_results_start + warning + table_start + table_rows + table_end + asn_results_end;

          $('#asn-results').replaceWith(modal_contents);

          // //$('#asn-results').append("Hello");
          // console.log("Completed")
        }).catch((err) => {
          console.log(err);
          $('#asn-results').replaceWith('<div id="asn-results"><div class="bg-danger text-white">WARNING: Supplied text did not resolve</br></div>');
        });  
      }

      function safety_catch(checkbox){
        if(safetycatch.checked) {
          $('#add-asn-modal-button').prop('disabled', false);
        } else {
          $('#add-asn-modal-button').prop('disabled', true);
        }
      };

      function disable_add_button(){
        $('#add-asn-modal-button').prop('disabled', true);
      }

      $(function() {
        // $('#lookup-button').click(trigger_lookup);
        $('#dismiss-button').click(clear_data);

      });
    </script>

{% endblock %}