synclias/blueprints/keywords/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, BooleanField, SubmitField, URLField, IntegerField, FormField, FieldList
from wtforms.validators import ValidationError, DataRequired, Email, EqualTo, Length, url

class AddKeywordForm(FlaskForm):
    keyword = StringField('Add Keyword', validators=[DataRequired()])
    exact = BooleanField('Exact Match?')
    submit = SubmitField('AddKeyword')

synclias/blueprints/keywords/views.py
from flask import Blueprint
from flask import request
from flask import flash, redirect, render_template, url_for, abort, jsonify

from flask_login import login_required

from .forms import AddKeywordForm

## App specific
from flask import current_app
from synclias import db
from sqlalchemy import select
from synclias.models import SafetyKeyword

keywords = Blueprint("keywords", __name__, template_folder="templates")

## Main Page
@keywords.route("/", methods=('GET',"POST"))
@login_required
def page():
    
    if request.method == "GET":
        page_id = request.args.get('page_id', 1, type=int)
        add_keyword_form = AddKeywordForm()

        safety_keywords = db.paginate((select(SafetyKeyword)).order_by(SafetyKeyword.keyword.asc()), page=page_id, per_page=10)

        next_url = url_for('keywords.page', page_id=safety_keywords.next_num) if safety_keywords.has_next else None
        prev_url = url_for('keywords.page', page_id=safety_keywords.prev_num) if safety_keywords.has_prev else None
        return render_template("/keyword.html",  safety_keywords=safety_keywords, add_keyword_form=add_keyword_form, next_url=next_url, prev_url=prev_url)

    else:

        ## POST - Adding keyword
        if not request.form:
            abort(400)
        to_add = request.form.get('keyword')
        in_db = db.session.query(SafetyKeyword).filter_by(keyword = to_add).first()
        if in_db:   
            flash(f"Keyword: \"{to_add}\" already present, ignoring", 'info')
            return redirect(url_for("keywords.page"))
        else:
            if 'exact' in request.form.keys():
                exact = 1
            else:
                exact = 0
            safety_keyword = SafetyKeyword(
                keyword=to_add, # type: ignore
                exact=exact, # type: ignore
            )
            db.session.add(safety_keyword)
            db.session.commit()
            return redirect(url_for("keywords.page"))

## Individual delete
@keywords.route('/delete/<int:id>', methods=["POST"])
@login_required
def delete(id):
    safety_keyword = db.get_or_404(SafetyKeyword, id)
    kw = safety_keyword.keyword
    db.session.delete(safety_keyword)
    db.session.commit()
    flash(f"Deleted: {kw}", 'info')
    return redirect(url_for("keywords.page"))

## Bulk delete - called by the "Delete Selected" button
@keywords.route('/delete/bulk/', methods=["POST"])
@login_required
def delete_bulk():
    
    if not request.form:
        abort(400)
    
    for key in request.form.keys():
        if key.startswith('select'):
            to_delete = key.split('-')[1]
            current_app.logger.info(f"Deleting Keyword: {to_delete}")
            safety_keyword = db.session.get(SafetyKeyword,to_delete)
            sk = safety_keyword.keyword # type: ignore
            db.session.delete(safety_keyword)
            db.session.commit()
            flash(f"Deleted: {sk}")
    return redirect(url_for("keywords.page"))


## Load suggestions from config/settings.py (Importend to app.config on startup)
@keywords.route('/create/suggestions', methods=["POST"])
@login_required
def keyword_add_suggestions():
  
    for suggestion in current_app.config['KEYWORD_SUGGESTIONS']:
        ## Test if it's already in there
        already_present = db.session.scalars(select(SafetyKeyword).where(SafetyKeyword.keyword == suggestion)).all()
        if already_present:
            flash(f"Already present: {suggestion}",category="info")
        else:
            current_app.logger.debug(already_present)
            new_keyword = SafetyKeyword(
                keyword = suggestion, # type: ignore
                exact = False, # type: ignore
            )
            db.session.add(new_keyword)

    ## ... can you tell "exact" got added later? will roll into the above, better, later 
    for suggestion in current_app.config['KEYWORD_SUGGESTIONS_EXACT']:
        ## Test if it's already in there
        already_present = db.session.scalars(select(SafetyKeyword).where(SafetyKeyword.keyword == suggestion)).first()
        if already_present:
            if already_present.exact == 0 or already_present.exact == False:
                already_present.exact = True
                db.session.commit()
                flash(f"Already present: {suggestion}, updated to exact match",category="info")
            else:
                flash(f"Already present: {suggestion}",category="info")
        else:
            current_app.logger.debug(already_present)
            new_keyword = SafetyKeyword(
                keyword = suggestion, # type: ignore
                exact = True, # type: ignore
            )
            db.session.add(new_keyword)

    # Commit and return       
    db.session.commit()
    return redirect(url_for("keywords.page"))

## Change an individual setting per site (e.g "exact match")
@keywords.route("/<string:option>/<int:id>/<int:new_state>", methods=['PUT'])
@login_required
def update_site_option(option,id,new_state):
    
    target = db.get_or_404(SafetyKeyword,id)

    if option == 'exact':
        current_app.logger.debug(f"Toggle keyword {id} option {option} to {new_state}")
        target.exact = new_state
        db.session.commit()
        return jsonify({ 'keyword' : id, 'option': 'exact', 'setting': new_state},200)
    else:
        abort(400)

synclias/blueprints/keywords/templates/keyword.html
{% extends "base.html" %}

{% block title %}Synclias{% endblock %}

{% block page_content %}

    <!-- Modal for Adding Excluded Keyword-->
    <div class="modal fade" id="add-keyword-modal" tabindex="-1" aria-labelledby="add-keyword-modal-label" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="add-keyword-modal-label">Add Safety Keyword</h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <form action="{{url_for('keywords.page')}}" method="post">
            {{ add_keyword_form.hidden_tag() }}
            <div class="modal-body">
              <div class="form-group row">
                {{ add_keyword_form.keyword.label }}
                <div class="col-xs-10">
                    {{ add_keyword_form.keyword(size=32,class="form-control") }}
                  
                    {% for error in add_keyword_form.keyword.errors %}
                    <span style="color: red;">[{{ error }}]</span>
                    {% endfor %}
                  </div>
                </div>
                <hr>
                <div class="form-group row">
                    <div class="form-check form-switch">
                    <!-- <div class="col-xs-10"> -->
                        <p>{{ add_keyword_form.exact.label }} {{ add_keyword_form.exact(class="form-check-input") }} </p>
                    <!-- </div> -->
                    </div>
                  </div>
                </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <button type="submit" class="btn btn-success">Add</button>
              </div>
            </form>
          </div>
        </div>
      </div>
      <!-- Modal End: Add Keyword-->
      
      <!-- Main Page Content Start -->
    </br>
    <h1>Safety Keywords</h1>

      <div class="row">

        </div>
        <div class="row">


          <div class="col-md-4">
            <form id="select-keywords" action="{{url_for('keywords.delete_bulk')}}" method="post">
            <table class="table table-striped" border="1">
              <thead>
                <tr>
                  <th colspan="1">
                    <div class="form-check">
                      <input class="form-check-input" type="checkbox" value="" onclick=toggle_selection(this.id,this.checked) name="check-all" id="check-all">
                        <label class="form-check-label" for="flexCheckDefault"></label>
                    </div>
                  </th>
                  <th>Keyword</th>
                  <th colspan="1"> Exact Match?</th>
                </tr>
              </thead>
              <tbody>
                {% for safety_keyword in safety_keywords %}
                <tr>
                  <td>
                     <div class="form-check">
                      <input class="form-check-input" type="checkbox" value="" name="select-{{safety_keyword.id}}" id="select-{{safety_keyword.id}}">
                        <label class="form-check-label" for="flexCheckDefault"></label>
                    </div>
                  </td>
                  <td>{{ safety_keyword.keyword }}</td>

                  <td>
                      <div class="form-check form-switch">
                      {% if safety_keyword.exact is true %}
                      <input class="form-check-input" type="checkbox" onclick="toggle_exact_match(this.id, this.checked)" name="exact-{{ safety_keyword.id }}" id="exact-{{ safety_keyword.id }}" checked="checked">
                      {% else %}
                      <input class="form-check-input" type="checkbox" onclick="toggle_exact_match(this.id, this.checked)" name="exact-{{ safety_keyword.id }}" id="exact-{{ safety_keyword.id }}" >
                      {% endif %}
                      </div>
                  </td>
              
                  <!-- Modal for deleting a site - required here to make all the ids line up-->
                  <div class="modal fade" id="deleteKeywordModal_{{ safety_keyword.id}}" tabindex="-1" aria-labelledby="deleteKeywordModal-label" aria-hidden="true">
                    <div class="modal-dialog">
                      <div class="modal-content">
                        <div class="modal-header">
                          <h5 class="modal-title" id="deleteKeywordModal-label">Delete Keyword</h5>
                          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                        </div>
                        <form action="{{url_for('keywords.delete', id=safety_keyword.id)}}" method="post">
                          <div class="modal-body">
                            <div class="form-group row">
                              <label class="col-sm-12 col-form-label">Do you want to delete the keyword <spa style='font-weight:bold;color:red'>{{safety_keyword.keyword}}</span>?</label>
                            </div>
                          </div>
                          <div class="modal-footer">
                            <button type="button" class="btn btn-default" data-bs-dismiss="modal">Close</button>
                            <button type="submit" class="btn btn-danger">Delete</button>
                          </div>
                        </form>
                      </div>
                    </div>
                  </div>
                <!-- End Modal-->
                </tr>
                {% endfor %}
              </tbody>
            </table>
          </form>

        </div>
        <div class="col-md-4 ">
          <table>
              <tr>
                <nav aria-label="..."> 
                  <ul class="pagination ">
                    <li class="page-item  {{'disabled' if not prev_url}}">
                      <a class="page-link" href="{{ prev_url }}">Prev</a>
                    </li>

                    {% for page_no in range(safety_keywords.pages) %}
                      {% if loop.index == safety_keywords.page %}
                        <li class="page-item active"> <span class="page-link"> {{ loop.index }} </span> </li>
                      {% else %}
                        <li class="page-item" ><a class="page-link" href="{{ url_for('keywords.page', page_id= loop.index) }}">{{ loop.index }}</a></li>
                      {% endif%}
                    {% endfor %}
                    <li class="page-item  {{'disabled' if not next_url}}">
                      <a class="page-link" href="{{ next_url }}">Next</a>
                    </li>
                  </ul>
                </nav>
          
              </tr>
              <tr>
                <button type="button" class="btn btn-success text-right" data-bs-toggle="modal" data-bs-target="#add-keyword-modal">
                Add Keyword
                </button>
              </tr>
              <tr><br><br></tr>
              <tr>              
                  <button type="submit" form="select-keywords" class="btn btn-danger">Delete Selected</button>
              </tr>
              <tr><br><br></tr>
              <tr>
                  <form action="{{url_for('keywords.keyword_add_suggestions')}}" method="post">
                    <button input type = submit class="btn btn-primary" id="change-admin-pass"> Import Suggestions </button>
                  </form>
              </tr>
            </table>
          </div>

      </div>
      <!-- Main Page Content End -->
{% endblock %}

{% block scripts %}

    {{ super() }}



    <script>

      // checkbox for "select all"
      function toggle_selection(id,checked){
        $("[name^='select-']").each(function(){
          this.checked = checked
        })
      }

      function toggle_exact_match(id,state){
        const splitArray = id.split("-");
        if (state == true){
          state_int = 1;
        } else {
          state_int = 0;
        }

        url = "/keyword/exact/";
        url = url + splitArray[1] + "/" + state_int;

        $.ajax({
          type: 'PUT',
          url: url, 
        });
      }
      </script>

{% endblock %}