synclias/blueprints/history/views.py
from flask import Blueprint
from flask import request
from flask import flash, redirect, render_template, url_for, abort, jsonify
import pickle
from flask_login import login_required

## App specific
from flask import current_app
from synclias import db
from sqlalchemy import select
from synclias.models import Result


history = Blueprint("history", __name__, template_folder="templates")

@history.route("/", methods=['GET'])
@login_required
def page():
    ## Parameter sanity checking
    if request.args.get('log_id') == "undefined":
        log_id = 0
    else:
        log_id = request.args.get('log_id', 0, type=int)
    hide_zero = request.args.get('hide_zero', 0, type=int)
    
    current_app.logger.info(f"Called history log id: {log_id}")
    
    ## Find what they asked for
    if log_id == 0:
        result_entry = db.session.query(Result).order_by(Result.id.desc()).first()
    else:
        result_entry = db.session.scalars(select(Result).where(Result.id == log_id)).first()

        ##Prevent an issue where "hide_zero" is toggled on, whilst a 0 change log is shown, bump to first log with changes
        if result_entry is not None and result_entry.changes == 0 and hide_zero == 1:
            result_entry = db.session.query(Result).where(Result.changes != 0).order_by(Result.id.desc()).first()
    
    ## If there's no logs, or we've filtered them out (no changes), report no logs
    if result_entry is None:
        current_app.logger.info("History - called, but no logs to display")
        return render_template("/no_logs.html", hide_zero=hide_zero, no_logs=True)

    ## Set log_id, it may not not be what originally asked for
    log_id = result_entry.id

    ## Load the object for the required log from the DB
    result_data = pickle.loads(result_entry.result_pickle) # type: ignore

    ## Stats to fill out the dropdown, make query, run query
    if hide_zero == 0:
        log_column_query = select(Result.id, Result.timestamp,Result.changes).order_by(Result.id.desc())
    else:
        log_column_query = select(Result.id, Result.timestamp,Result.changes).where(Result.changes != 0).order_by(Result.id.desc())
    
    log_list = db.session.execute(log_column_query).all()

    ## Final sanity check, I think this is redundant after checks above, will test before removing
    if len(log_list) == 0:
        no_logs = True
        return render_template("/no_logs.html", log_id=log_id,hide_zero=hide_zero, no_logs=True)
    else:
        no_logs = False

    return render_template("/history.html", result_data=result_data, log_list=log_list, log_id=log_id, hide_zero=hide_zero, no_logs=no_logs)

synclias/blueprints/scanner/views.py
from flask import Blueprint
from flask import request
from flask import url_for, jsonify, render_template

from flask_login import login_required
from .forms import ScannerForm

from flask import current_app

scanner = Blueprint("scanner", __name__, template_folder="templates")

@scanner.route("/", methods=('GET', 'POST'))
@login_required
def page():
    form = ScannerForm()
    
    ## First call with a get
    if request.method == "GET":
        return render_template("/scanner.html", form=form)

    ## If they posted ok, popup with a modal for the scan 
    if form.validate_on_submit():
        return render_template("/scanner.html", form=form, start_scan=True)
    else:
        ## Re-send the initial core with error
        return render_template("/scanner.html", form=form)

@scanner.route("/scan/", methods=['POST'])
@login_required
def scan():

    req_json = request.get_json()

    if req_json['safe_scan']:
        current_app.logger.info(f"Safe")
        safe = True
    else:
        current_app.logger.info(f"Unsafe")
        safe = False
    
    from .tasks import scanner_bg
    task = scanner_bg.delay(req_json['site'],safe)
    return jsonify({}), 202, {'Location': url_for('scanner.taskstatus', task_id=task.id)}


@scanner.route('/scanner/scan/status/<task_id>', methods=['GET','POST'])
@login_required
def taskstatus(task_id):
    from synclias.blueprints.scanner.tasks import scanner_bg
    task = scanner_bg.AsyncResult(task_id)
    if task.state == 'PENDING':
        # job did not start yet
        response = {
            'state': task.state,
            'sites': 0,
            'scan_rcode' : 202,
            'notes' : '',
            'status': 'Pending...'
        }
    elif task.state != 'FAILURE':
        response = {
            'state': task.state,
            'sites': task.info.get('sites', 0),
            'scan_rcode': task.info.get('scan_rcode', 1),
            'notes' : task.info.get('notes', 2),
            'status': task.info.get('status', '')
        }
        if 'result' in task.info:
            response['result'] = task.info['result']
    else:
        # something went wrong in the background job
        response = {
            'state': task.state,
            'current': 7,
            'scan_rcode': task.info.get('scan_rcode', 1),
            'notes' : '',
            'status': str(task.info), 
        }
    return jsonify(response)

synclias/blueprints/syncer/views.py
from flask import Blueprint
from flask import url_for, abort, jsonify
from flask import session
from flask_login import login_required

syncer = Blueprint("syncer", __name__, template_folder="templates")

## Start sync, return task id for monitoring
@syncer.route('/sync', methods=['POST'])
@login_required
def sync():
    from .tasks import run_syncer
    task = run_syncer.delay()
    return jsonify({}), 202, {'Location': url_for('syncer.taskstatus', task_id=task.id)}

## Report current state of task, called by ajax request
@syncer.route('/sync/status/<task_id>', methods=['GET'])
@login_required
def taskstatus(task_id):
    from .tasks import run_syncer
    task = run_syncer.AsyncResult(task_id)
    if task.state == 'PENDING':
        # job did not start yet
        response = {
            'state': task.state,
            'current': 0,
            'total': 7,
            'subtask_current' : 0,
            'subtask_total' : 1,
            'status': 'Pending...'
        }
    elif task.state != 'FAILURE':
        response = {
            'state': task.state,
            'current': task.info.get('current', 0),
            'total': task.info.get('total', 1),
            'subtask_current' : task.info.get('subtask_current', 0),
            'subtask_total' : task.info.get('subtask_total',1),
            'status': task.info.get('status', '')
        }
        if 'result' in task.info:
            response['result'] = task.info['result']
    else:
        # something went wrong in the background job
        response = {
            'state': task.state,
            'current': 7,
            'total': 7,
            'subtask_current' : 0,
            'subtask_total' : 1,
            'status': str(task.info),  # this is the exception raised
        }
        session['sync_task_id'] = "Blank"
    return jsonify(response)

synclias/templates/bootstrap/base.html
<!doctype html>
<html lang="en" data-bs-theme="dark" >
    <head>
        {% block head %}
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        {% block styles %}
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-sRIl4kxILFvY47J16cr9ZwB07vP4J8+LH7qKQnuqkuIAvNWLzeN8tE5YBujZqJLB" crossorigin="anonymous">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.13.1/font/bootstrap-icons.min.css" rel="stylesheet">
        <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}">

        {% endblock %}
        
        {% endblock %}

    </head>
    <body>
 
        <nav class="navbar navbar-expand-sm bg-body-tertiary" data-bs-theme="dark">
        <div class="container-fluid">
            <a class="navbar-brand">Synclias</a>
            {% if current_user.is_anonymous %}
            {% else %}
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation" >
            <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="/">Home</a>
                </li>
                <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{{url_for('scanner.page')}}">Scanner</a>
                </li>
                <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{{url_for('sites.site')}}">Sites</a>
                </li>
                <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{{url_for('keywords.page')}}">Keywords</a>
                </li>
                <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{{url_for('asns.page')}}">ASNs</a>
                </li>
                <!-- <li class="nav-item">
                <a class="nav-link" href="{{url_for('history.page')}}">History</a>
                </li> -->
                <li class="nav-item">
                <a class="nav-link active" href="{{url_for('core.settings')}}">Settings</a>
                </li>
                 <li class="nav-item dropdown">

                      <a class="btn dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-bs-toggle="dropdown" aria-expanded="false">
                        History
                        </a>
                    <ul class="dropdown-menu dropdown-menu-dark">
                        <li><a class="nav-link" href="{{url_for('history.page')}}">Sync History</a></li>
                        <li><a class="nav-link" href="{{url_for('ip_history.page')}}">IP Tracking</a></li>
                    </ul>
                </li>

                <li></li>
            </ul>
            </div>
                
                <div class="col-12 col-lg-auto">
                    <a href="{{url_for('auth.logout')}}" class="btn btn btn-outline-primary my-2 my-sm-0">Logout</a>
                    <button class="btn btn-primary my-2 my-sm-0" id="start-sync">Sync</button>
                </div>
            </div>
            {% endif %}
        </nav>

        {% with messages = get_flashed_messages() %}
        {% if messages %}
            <ul class=flashes>
                <div class="alert alert-warning">
                {% for message in messages %}
                    <li class="list-group-item"></li>
                        {{message}}
                    </li>
                {% endfor %}    
                </div>
                <!-- <li>{{ message }}</li> -->
            </ul>
        {% endif %}
        {% endwith %}

        <div class="toast-container position-fixed top-0 end-0 p-3">
            <div id="syncToast" class="toast" role="alert" aria-live="assertive" aria-atomic="true" data-bs-autohide="false">
                <div class="toast-header">
                <strong class="me-auto">Sync</strong>
                <small>Running</small>
                <button type="button" class="btn-close" data-bs-dismiss="toast" aria-label="Close"></button>
                </div>
                <div class="toast-body">
                    <div id="sync-status"></div>
                </div>
            </div>
        </div>

        {% block content %}
 
        <!-- Your page content -->
        {% endblock %}

        {% block scripts %}
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
        <script src="//cdnjs.cloudflare.com/ajax/libs/nanobar/0.2.1/nanobar.min.js"></script>
        <script>
            function setCookie(cname, cvalue) {
                document.cookie = cname + "=" + cvalue;
            }
            
            function getCookie(cname) {
                let name = cname + "=";
                let decodedCookie = decodeURIComponent(document.cookie);
                let ca = decodedCookie.split(';');
                for(let i = 0; i <ca.length; i++) {
                    let c = ca[i];
                    while (c.charAt(0) == ' ') {
                    c = c.substring(1);
                    }
                    if (c.indexOf(name) == 0) {
                    return c.substring(name.length, c.length);
                    }
                }
                return "";
            }
                            
            function checkSyncCookies() {
                status_url = getCookie("SyncTask");
                if (status_url != ""){
                    console.log("Running Synctask: " + status_url);

                    // Flagged a running task, go get the status:
                    $.getJSON(status_url, function(data) {
                        console.log("Checking task")
                        console.log(data)

                        if (data['state'] == 'PENDING' || data['state'] == 'PROGRESS') {
                            console.log("Task is progressing")
                            const toastLiveExample = document.getElementById('syncToast');
                            const toastBootstrap = bootstrap.Toast.getOrCreateInstance(toastLiveExample);
                            toastBootstrap.show();
                            div = $('<div id="sync-status"><div><div>Picking up Sync....</div></div><cr></cr><div class="progress"><div class="progress-bar progress-bar-striped progress-bar-animated" id="sync-progress" role="progressbar" style="width: 0%"></div></div></div></div>');
                            $('#sync-status').replaceWith(div);

                            update_progress(status_url, div[0]);
                        } else {
                            // Not running anymore, clear the cookie
                            setCookie("SyncTask","")
                        }
                    })

                } else {
                    console.log("No cookie for synctask");
                }
            }
               
            $(function() {
                console.log( "ready!" );
                checkSyncCookies();
            });

            function trigger_sync() {
                console.log("sync triggered!")

                const toastLiveExample = document.getElementById('syncToast');
                const toastBootstrap = bootstrap.Toast.getOrCreateInstance(toastLiveExample);
                toastBootstrap.show();

                // add task status elements
                div = $('<div id="sync-status"><div><div>Syncing....</div></div><cr></cr><div class="progress"><div class="progress-bar progress-bar-striped progress-bar-animated" id="sync-progress" role="progressbar" style="width: 0%"></div></div></div></div>');
                $('#sync-status').replaceWith(div);

                // send ajax POST request to start background job
                $.ajax({
                    type: 'POST',
                    url: "{{url_for('syncer.sync')}}",
                    success: function(data, status, request) {
                        status_url = request.getResponseHeader('Location');
                        setCookie("SyncTask",status_url);
                        update_progress(status_url, div[0]);
                    },
                    error: function() {
                        alert('Unexpected error');
                    }
                });
            }
            function update_progress(status_url, status_div) {
                // send GET request to status URL
                $.getJSON(status_url, function(data) {
                    // update UI
                    step = "Step: " + data['current'] + '/' + data['total'] + " - " + data['status'];
                    percent = parseInt(data['subtask_current'] * 100 / data['subtask_total']);
                    document.getElementById('sync-progress').style = "width: "+ percent +"%";
                    console.log(percent);
                    $(status_div.childNodes[0]).text(step);
                    if (data['state'] != 'PENDING' && data['state'] != 'PROGRESS') {
                        if ('result' in data) {
                            // show result
                            $(status_div.childNodes[3]).text('Result: ' + data['result']);
                            setTimeout(function() {
                                const toastLiveExample = document.getElementById('syncToast');
                                const toastBootstrap = bootstrap.Toast.getOrCreateInstance(toastLiveExample);
                                toastBootstrap.hide();
                            }, 3000);
                        }
                        else {
                            // something unexpected happened
                            $(status_div.childNodes[3]).text('Result: ' + data['state']);
                        }
                    }
                    else {
                        // rerun in 2 seconds
                        setTimeout(function() {
                            update_progress(status_url, status_div);
                        }, 500);
                    }
                });
            }


            $(function() {
                $('#start-sync').click(trigger_sync);
            });
        </script>
        {% endblock %}
    </body>
</html>